[profile Tomorrow Night Blue]
fg = FFFFFF
bg = 002451
cursor-color = FFEEAD
palette = 0,000000,1,FF9DA4,2,D1F1A9,3,FFEEAD,4,BBDAFF,5,EBBBFF,6,99FFFF,7,FFFFFF,8,000000,9,FF9DA4,10,D1F1A9,11,FFEEAD,12,BBDAFF,13,EBBBFF,14,99FFFF,15,FFFFFF
