[colors.primary]
foreground = "#3760bf"
background = "#e1e2e7"

[colors.cursor]
text = "#e1e2e7"
cursor = "#3760bf"

[colors.selection]
text = "#3760bf"
background = "#b7c1e3"

[colors.normal]
black = "#b4b5b9"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
white = "#6172b0"

[colors.bright]
black = "#a1a6c5"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
white = "#3760bf"
