[colors.primary]
foreground = "#4f5b62"
background = "#faf3e1"

[colors.cursor]
text = "#faf3e1"
cursor = "#4f5b62"

[colors.selection]
text = "#4f5b62"
background = "#d3dfe6"

[colors.normal]
black = "#faf3e1"
red = "#f85550"
green = "#8da200"
yellow = "#dea000"
blue = "#3a94c4"
magenta = "#df69ba"
cyan = "#36a87e"
white = "#4f5b62"

[colors.bright]
black = "#dbc988"
red = "#e6271c"
green = "#758700"
yellow = "#b98500"
blue = "#297ca6"
magenta = "#ca43a3"
cyan = "#258c67"
white = "#6e7f88"
