[colors.primary]
foreground = "#353535"
background = "#eeeeee"

[colors.cursor]
text = "#eeeeee"
cursor = "#353535"

[colors.selection]
text = "#353535"
background = "#d7d7d7"

[colors.normal]
black = "#eeeeee"
red = "#a8334c"
green = "#4f6c31"
yellow = "#944927"
blue = "#286486"
magenta = "#88507d"
cyan = "#3b8992"
white = "#353535"

[colors.bright]
black = "#c6c3c3"
red = "#94253e"
green = "#3f5a22"
yellow = "#803d1c"
blue = "#1d5573"
magenta = "#7b3b70"
cyan = "#2b747c"
white = "#5c5c5c"
