#!/usr/bin/env python3
"""demo/tour_themes.inc from themes/*.conf: the colours of the themes the
UPDemo tour switches between live (OSC 4 / 10 / 11), so the tour shows the
kit's themes exactly and cannot drift from them (one source of truth).

Run by make when a theme changes; the output is committed, as
engine/vtcaps.inc is, so a build needs no Python.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
THEMES = ["dracula-default", "solarized-dark", "gruvbox-dark", "nord-default"]
OUT = ROOT / "demo" / "tour_themes.inc"


def load(name):
    """name's display name, fg, bg and the 16 palette entries, as RRGGBB."""
    title, keys = "", {}
    for line in (ROOT / "themes" / (name + ".conf")).read_text().splitlines():
        line = line.strip()
        if line.startswith("[profile ") and line.endswith("]"):
            title = line[len("[profile "):-1]
        elif "=" in line:
            k, v = line.split("=", 1)
            keys[k.strip()] = v.strip()
    pal = keys["palette"].split(",")
    colours = dict(zip(pal[0::2], pal[1::2]))
    return title, keys["fg"], keys["bg"], [colours[str(i)] for i in range(16)]


def main():
    out = ["/* Generated by tools/gen_tour_themes.py from the .conf files in themes/. Do not edit. */",
           "static const struct tour_theme {",
           "    const char *name;",
           "    const char *fg, *bg;",
           "    const char *pal[16];",
           "} tour_themes[] = {"]
    for n in THEMES:
        title, fg, bg, pal = load(n)
        out.append('    { "%s", "%s", "%s",' % (title, fg, bg))
        out.append("      { " + ", ".join('"%s"' % p for p in pal[:8]) + ",")
        out.append("        " + ", ".join('"%s"' % p for p in pal[8:]) + " } },")
    out.append("};")
    OUT.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
