#!/usr/bin/env python3
"""Generate render/glyph_tables.inc from the Unicode character names, so the
box-drawing and block tables cannot drift from the standard by a typo.

Box drawing U+2500-U+257F: one byte per code point, two bits per arm
(up 0-1, right 2-3, down 4-5, left 6-7): 0 none, 1 light, 2 heavy, 3 double.
The three diagonals are 0 here (drawn separately). Dashed forms are drawn
solid; arcs as corners.

Blocks U+2580-U+259F: one byte each:
  0x80 | n        shade, n = 1 light, 2 medium, 3 dark
  0x40 | mask     quadrants, mask bits 1 upper left, 2 upper right,
                  4 lower left, 8 lower right
  side << 4 | k   a bar of k eighths against side 0 top, 1 bottom, 2 left, 3 right
"""
import pathlib, re, unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent
W = {"LIGHT": 1, "SINGLE": 1, "HEAVY": 2, "DOUBLE": 3}
DIRS = {"UP": ["UP"], "DOWN": ["DOWN"], "LEFT": ["LEFT"], "RIGHT": ["RIGHT"],
        "HORIZONTAL": ["LEFT", "RIGHT"], "VERTICAL": ["UP", "DOWN"]}
SHIFT = {"UP": 0, "RIGHT": 2, "DOWN": 4, "LEFT": 6}
EIGHTHS = {"ONE": 1, "TWO": 2, "THREE": 3, "FOUR": 4, "FIVE": 5, "SIX": 6, "SEVEN": 7}

def box(cp):
    name = unicodedata.name(chr(cp))
    assert name.startswith("BOX DRAWINGS "), name
    n = name[len("BOX DRAWINGS "):]
    if "DIAGONAL" in n:
        return 0
    for junk in ("DOUBLE DASH ", "TRIPLE DASH ", "QUADRUPLE DASH ", "ARC "):
        n = n.replace(junk, "")
    toks = [t for t in n.split() if t != "AND"]
    arms = {}
    if toks[0] in W:  # "HEAVY UP AND LIGHT DOWN": a weight governs the dirs after it
        cur = None
        for t in toks:
            if t in W:
                cur = W[t]
            else:
                for d in DIRS[t]:
                    arms[d] = cur
    else:             # "DOWN HEAVY AND RIGHT LIGHT": dirs take the weight after them
        pend = []
        for t in toks:
            if t in W:
                for d in pend:
                    arms[d] = W[t]
                pend = []
            else:
                pend += DIRS[t]
        assert not pend, name
    v = 0
    for d, w in arms.items():
        v |= w << SHIFT[d]
    assert v, name
    return v

def block(cp):
    name = unicodedata.name(chr(cp))
    if name.endswith(" SHADE"):
        return 0x80 | {"LIGHT": 1, "MEDIUM": 2, "DARK": 3}[name.split()[0]]
    if name.startswith("QUADRANT "):
        mask = 0
        for part in name[len("QUADRANT "):].split(" AND "):
            mask |= {"UPPER LEFT": 1, "UPPER RIGHT": 2, "LOWER LEFT": 4, "LOWER RIGHT": 8}[part]
        return 0x40 | mask
    if name == "FULL BLOCK":
        return (0 << 4) | 8
    t = name.split()
    side = {"UPPER": 0, "LOWER": 1, "LEFT": 2, "RIGHT": 3}[t[0]]
    k = 4 if t[1] == "HALF" else EIGHTHS[t[1]]
    return (side << 4) | k

def main():
    boxes = [box(cp) for cp in range(0x2500, 0x2580)]
    blocks = [block(cp) for cp in range(0x2580, 0x25A0)]
    out = ["/* Generated by tools/gen_glyph_tables.py from the Unicode names. Do not edit. */",
           "static const vt_u8 box_arms[128] = {"]
    for i in range(0, 128, 8):
        out.append("    " + ", ".join("0x%02X" % b for b in boxes[i:i + 8]) + ",  /* U+%04X */" % (0x2500 + i))
    out.append("};")
    out.append("static const vt_u8 block_shape[32] = {")
    for i in range(0, 32, 8):
        out.append("    " + ", ".join("0x%02X" % b for b in blocks[i:i + 8]) + ",  /* U+%04X */" % (0x2580 + i))
    out.append("};")
    # CP437 0x80-0xFF sorted by code point, for a binary search: read from
    # the engine's decode table so the two cannot drift apart.
    src = (ROOT / "engine/vtengine.c").read_text()
    body = src.split("static const vt_u16 cp437_hi[128] = {", 1)[1].split("};", 1)[0]
    hi = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]{4})", body)]
    assert len(hi) == 128 and len(set(hi)) == 128, len(hi)
    pairs = sorted((cp, 0x80 + i) for i, cp in enumerate(hi))
    out.append("/* CP437 0x80-0xFF by code point (from vtengine.c cp437_hi), for a binary search. */")
    out.append("static const vt_u16 cp437_rev_cp[128] = {")
    for i in range(0, 128, 8):
        out.append("    " + ", ".join("0x%04X" % c for c, _ in pairs[i:i + 8]) + ",")
    out.append("};")
    out.append("static const vt_u8 cp437_rev_byte[128] = {")
    for i in range(0, 128, 8):
        out.append("    " + ", ".join("0x%02X" % b for _, b in pairs[i:i + 8]) + ",")
    out.append("};")
    # Canonical compositions (base, mark) -> precomposed, for a combining
    # mark the bitmap font cannot draw over its letter: e + U+0301 is
    # drawn as U+00E9. Pairs whose result is NFC, below U+2000 (Latin,
    # Greek, Cyrillic and the rest the outline font may hold); a mark
    # sequence composes one pair at a time (Vietnamese).
    comp = []
    for c in range(0x80, 0x2000):
        d = unicodedata.decomposition(chr(c))
        if not d or d.startswith("<"):
            continue
        p = [int(x, 16) for x in d.split()]
        if len(p) == 2 and unicodedata.normalize("NFC", chr(p[0]) + chr(p[1])) == chr(c):
            comp.append(((p[0] << 16) | p[1], c))
    comp.sort()
    out.append("/* Canonical compositions: (base << 16 | mark) -> the precomposed character. */")
    out.append("#define COMPOSE_N %d" % len(comp))
    out.append("static const vt_u32 compose_key[%d] = {" % len(comp))
    for i in range(0, len(comp), 6):
        out.append("    " + ", ".join("0x%08XUL" % k for k, _ in comp[i:i + 6]) + ",")
    out.append("};")
    out.append("static const vt_u16 compose_to[%d] = {" % len(comp))
    for i in range(0, len(comp), 10):
        out.append("    " + ", ".join("0x%04X" % v for _, v in comp[i:i + 10]) + ",")
    out.append("};")
    (ROOT / "render/glyph_tables.inc").write_text("\n".join(out) + "\n")
    print("box: %d, blocks: %d" % (len(boxes), len(blocks)))

if __name__ == "__main__":
    main()
