#!/usr/bin/env python3
"""engine/vtcaps.inc from terminfo/vtcon.terminfo: the capabilities XTGETTCAP
(DCS + q) answers, so the engine says exactly what the terminfo entry says
(one source of truth; tests/test_protocol.c checks the two against each other).

Run by make when the terminfo changes; the output is committed, as
render/glyph_tables.inc is, so a build needs no Python.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "terminfo", "vtcon.terminfo")
OUT = os.path.join(HERE, "..", "engine", "vtcaps.inc")


def unescape(v):
    """A terminfo string value as its bytes (terminfo(5) escapes)."""
    out = bytearray()
    i = 0
    simple = {"E": 0x1B, "e": 0x1B, "n": 0x0A, "l": 0x0A, "r": 0x0D, "t": 0x09, "b": 0x08,
              "f": 0x0C, "s": 0x20, "^": 0x5E, "\\": 0x5C, ",": 0x2C, ":": 0x3A}
    while i < len(v):
        c = v[i]
        if c == "\\" and i + 1 < len(v):
            d = v[i + 1]
            if d in simple:
                out.append(simple[d])
                i += 2
                continue
            if d.isdigit():
                j = i + 1
                while j < len(v) and j < i + 4 and v[j] in "01234567":
                    j += 1
                n = int(v[i + 1:j], 8)
                out.append(0x80 if n == 0 else n)  # \0 is \200, as ncurses has it
                i = j
                continue
            out.append(ord(d))
            i += 2
            continue
        if c == "^" and i + 1 < len(v):
            d = v[i + 1]
            out.append(0x7F if d == "?" else ord(d.upper()) & 0x1F)
            i += 2
            continue
        out.append(ord(c))
        i += 1
    return bytes(out)


def capabilities(text):
    """(name, kind, value) for each capability of the entry: kind b, n, s."""
    body = []
    first = True
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if first:  # the names line
            first = False
            continue
        body.append(line.strip())
    caps, cur, i, s = [], "", 0, " ".join(body)
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            cur += s[i:i + 2]
            i += 2
            continue
        if c == ",":
            if cur.strip():
                caps.append(cur.strip())
            cur = ""
        else:
            cur += c
        i += 1
    out = []
    for c in caps:
        if "=" in c:
            n, v = c.split("=", 1)
            out.append((n, "s", unescape(v)))
        elif "#" in c:
            n, v = c.split("#", 1)
            out.append((n, "n", str(int(v, 0)).encode()))
        elif not c.endswith("@"):
            out.append((c, "b", b""))
    return out


def c_string(b):
    s = '"'
    for x in b:
        ch = chr(x)
        if ch in '"\\?' or x < 0x20 or x >= 0x7F:
            s += "\\%03o" % x  # octal, and ? too: no trigraphs
        else:
            s += ch
    return s + '"'


def main():
    with open(SRC) as f:
        caps = capabilities(f.read())
    rows = ["/* Generated by tools/gen_vtcaps.py from terminfo/vtcon.terminfo -- do not edit.",
            " * XTGETTCAP's answers: name, kind (b boolean, n number, s string), value. */"]
    for n, k, v in caps:
        rows.append("    { %s, '%s', %s }," % (c_string(n.encode()), k, c_string(v)))
    with open(OUT, "w") as f:
        f.write("\n".join(rows) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
