#!/usr/bin/env python3
"""Generate engine/vtwidth.h: the display width of a code point.

The rules are glibc's (localedata/unicode-gen/utf8_gen.py, write_header_width),
in order of precedence, so that the terminal counts cells as the remote
program's wcwidth() does:

  U+00AD SOFT HYPHEN                                 1
  U+115F HANGUL CHOSEONG FILLER                      2
  Hangul jungseong / jongseong (HangulSyllableType V, T)   0
  General_Category Mn, Me                            0
  Default_Ignorable_Code_Point                       0
  East_Asian_Width W, F                              2
  everything else                                    1

The UCD files are fetched once into build/ucd/<version>/.
    python3 tools/gen_width.py [VERSION]      (default 16.0.0)
"""
import os
import re
import sys
import urllib.request

VERSION = sys.argv[1] if len(sys.argv) > 1 else "16.0.0"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "build", "ucd", VERSION)
FILES = {
    "EastAsianWidth.txt": "EastAsianWidth.txt",
    "DerivedCoreProperties.txt": "DerivedCoreProperties.txt",
    "HangulSyllableType.txt": "HangulSyllableType.txt",
    "DerivedGeneralCategory.txt": "extracted/DerivedGeneralCategory.txt",
}


def ucd(name):
    path = os.path.join(CACHE, name)
    if not os.path.exists(path):
        os.makedirs(CACHE, exist_ok=True)
        url = "https://www.unicode.org/Public/%s/ucd/%s" % (VERSION, FILES[name])
        with urllib.request.urlopen(url) as r, open(path, "wb") as f:
            f.write(r.read())
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            fields = [x.strip() for x in line.split(";")]
            m = re.match(r"([0-9A-F]+)(?:\.\.([0-9A-F]+))?$", fields[0])
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            yield lo, hi, fields[1:]


def ranges(cps):
    out = []
    for c in sorted(cps):
        if out and out[-1][1] == c - 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


def main():
    width = {}
    for lo, hi, f in ucd("EastAsianWidth.txt"):
        if f[0] in ("W", "F"):
            for c in range(lo, hi + 1):
                width[c] = 2
    for lo, hi, f in ucd("DerivedCoreProperties.txt"):
        if f[0] == "Default_Ignorable_Code_Point":
            for c in range(lo, hi + 1):
                width[c] = 0
    for lo, hi, f in ucd("DerivedGeneralCategory.txt"):
        if f[0] in ("Mn", "Me"):
            for c in range(lo, hi + 1):
                width[c] = 0
    for lo, hi, f in ucd("HangulSyllableType.txt"):
        if f[0] in ("V", "T"):
            for c in range(lo, hi + 1):
                width[c] = 0
    width[0x115F] = 2
    width[0x00AD] = 1
    zero = ranges(c for c, w in width.items() if w == 0)
    wide = ranges(c for c, w in width.items() if w == 2)
    assert min(c for c, w in width.items() if w != 1) >= 0x300, "vt_char_width's fast path"

    def table(name, rs):
        lines = ["static const vt_u32 %s[][2] = {" % name]
        row = []
        for lo, hi in rs:
            row.append("{ 0x%05X, 0x%05X }" % (lo, hi))
            if len(row) == 4:
                lines.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ", ".join(row) + ",")
        lines.append("};")
        return "\n".join(lines)

    out = """/* vtwidth.h -- how many cells a code point takes on a vtcon terminal.
 * GENERATED by tools/gen_width.py from the Unicode %(v)s character database;
 * do not edit, run the generator.
 *
 * One definition for the engine and for programs that lay text out for it
 * (tmux on AmigaOS: its idea of a width must be the terminal's, or its panes
 * drift from what XCON draws). Header-only so a port compiles it without the
 * engine; needs vt_u32 (vtengine.h) or a typedef of its own.
 *
 * The rules are glibc's wcwidth (localedata/unicode-gen/utf8_gen.py), so the
 * terminal counts cells as the remote program does:
 *   U+00AD 1; U+115F 2; Hangul jungseong and jongseong 0; marks Mn, Me 0;
 *   Default_Ignorable_Code_Point 0 (ZWJ, variation selectors); East Asian
 *   Wide and Fullwidth 2 (every Emoji_Presentation emoji is W); else 1.
 * A variation selector 16 does not widen its base: glibc and xterm count
 * U+2764 U+FE0F as one cell (foot and kitty widen it only in grapheme mode,
 * ?2027). */
#ifndef VTWIDTH_H
#define VTWIDTH_H

%(zero)s

%(wide)s

static int vt_width_in(vt_u32 c, const vt_u32 (*t)[2], int n)
{
    int lo = 0, hi = n - 1;
    if (c < t[0][0] || c > t[n - 1][1])
        return 0;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (c > t[mid][1])
            lo = mid + 1;
        else if (c < t[mid][0])
            hi = mid - 1;
        else
            return 1;
    }
    return 0;
}

/* Display width: 0, 1 or 2 cells. */
static int vt_char_width(vt_u32 c)
{
    if (c < 0x300)
        return 1;
    if (vt_width_in(c, vt_width_zero, (int)(sizeof(vt_width_zero) / sizeof(vt_width_zero[0]))))
        return 0;
    if (vt_width_in(c, vt_width_wide, (int)(sizeof(vt_width_wide) / sizeof(vt_width_wide[0]))))
        return 2;
    return 1;
}

#endif
""" % {"v": VERSION, "zero": table("vt_width_zero", zero), "wide": table("vt_width_wide", wide)}
    with open(os.path.join(ROOT, "engine", "vtwidth.h"), "w") as f:
        f.write(out)
    print("engine/vtwidth.h: Unicode %s, %d zero-width ranges, %d wide ranges"
          % (VERSION, len(zero), len(wide)))


if __name__ == "__main__":
    main()
