#!/usr/bin/env python3
"""Generate engine/vtwidth.h: the display width of a code point.

The rules are glibc's (localedata/unicode-gen/utf8_gen.py, write_header_width),
in order of precedence, so that the terminal counts cells as the remote
program's wcwidth() does:

  U+00AD SOFT HYPHEN                                 1
  U+115F HANGUL CHOSEONG FILLER                      2
  Hangul jungseong / jongseong (HangulSyllableType V, T)   0
  General_Category Mn, Me                            0
  Default_Ignorable_Code_Point                       0
  East_Asian_Width W, F                              2
  everything else                                    1

The UCD files are fetched once into build/ucd/<version>/.
    python3 tools/gen_width.py [VERSION]      (default 16.0.0)
"""
import os
import re
import sys
import urllib.request

VERSION = sys.argv[1] if len(sys.argv) > 1 else "16.0.0"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "build", "ucd", VERSION)
FILES = {
    "EastAsianWidth.txt": "EastAsianWidth.txt",
    "DerivedCoreProperties.txt": "DerivedCoreProperties.txt",
    "HangulSyllableType.txt": "HangulSyllableType.txt",
    "DerivedGeneralCategory.txt": "extracted/DerivedGeneralCategory.txt",
}


def ucd(name):
    path = os.path.join(CACHE, name)
    if not os.path.exists(path):
        os.makedirs(CACHE, exist_ok=True)
        url = "https://www.unicode.org/Public/%s/ucd/%s" % (VERSION, FILES[name])
        with urllib.request.urlopen(url) as r, open(path, "wb") as f:
            f.write(r.read())
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            fields = [x.strip() for x in line.split(";")]
            m = re.match(r"([0-9A-F]+)(?:\.\.([0-9A-F]+))?$", fields[0])
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            yield lo, hi, fields[1:]


def main():
    width = {}
    for lo, hi, f in ucd("EastAsianWidth.txt"):
        if f[0] in ("W", "F"):
            for c in range(lo, hi + 1):
                width[c] = 2
    for lo, hi, f in ucd("DerivedCoreProperties.txt"):
        if f[0] == "Default_Ignorable_Code_Point":
            for c in range(lo, hi + 1):
                width[c] = 0
    for lo, hi, f in ucd("DerivedGeneralCategory.txt"):
        if f[0] in ("Mn", "Me"):
            for c in range(lo, hi + 1):
                width[c] = 0
    for lo, hi, f in ucd("HangulSyllableType.txt"):
        if f[0] in ("V", "T"):
            for c in range(lo, hi + 1):
                width[c] = 0
    width[0x115F] = 2
    width[0x00AD] = 1

    # Laid out for a lookup without a search (the engine asks for every
    # character outside ASCII): code points below LIMIT in pages of 256,
    # each page all one width or 2 bits a code point; above it only the
    # tag / variation selector plane-14 block differs from 1.
    LIMIT = 0x40000
    w = lambda c: width.get(c, 1)
    assert min(c for c in width if width[c] != 1) >= 0x300, "vt_char_width's fast path"
    high = sorted(c for c in width if c >= LIMIT and width[c] != 1)
    assert high == list(range(0xE0000, 0xE1000)) and all(width[c] == 0 for c in high), \
        "beyond U+3FFFF only U+E0000..E0FFF (width 0) is expected"
    index, pages = [], []
    for p in range(LIMIT // 256):
        ws = [w(c) for c in range(p * 256, p * 256 + 256)]
        if len(set(ws)) == 1:
            index.append({1: 0, 2: 1, 0: 2}[ws[0]])
            continue
        bits = []
        for i in range(0, 256, 4):
            b = 0
            for k in range(4):
                b |= ws[i + k] << (2 * k)
            bits.append(b)
        if bits not in pages:
            pages.append(bits)
        index.append(3 + pages.index(bits))
    assert 3 + len(pages) <= 256

    def rows(vals, per, fmt):
        out = []
        for i in range(0, len(vals), per):
            out.append("    " + ", ".join(fmt % v for v in vals[i:i + per]) + ",")
        return "\n".join(out)

    page_tab = "static const unsigned char vt_width_page[%d] = {\n%s\n};" % (len(index), rows(index, 16, "%d"))
    bits_tab = "static const unsigned char vt_width_bits[%d][64] = {\n%s\n};" % (
        len(pages), "\n".join("    {\n" + rows(p, 16, "0x%02X").replace("    ", "        ") + "\n    },"
                              for p in pages))

    out = """/* vtwidth.h -- how many cells a code point takes on a vtcon terminal.
 * GENERATED by tools/gen_width.py from the Unicode %(v)s character database;
 * do not edit, run the generator (make widths).
 *
 * One definition for the engine and for programs that lay text out for it
 * (tmux on AmigaOS: its idea of a width must be the terminal's, or its panes
 * drift from what XCON draws). Header-only so a port compiles it without the
 * engine; needs vt_u32 (vtengine.h) or a typedef of its own.
 *
 * The rules are glibc's wcwidth (localedata/unicode-gen/utf8_gen.py), so the
 * terminal counts cells as the remote program does:
 *   U+00AD 1; U+115F 2; Hangul jungseong and jongseong 0; marks Mn, Me 0;
 *   Default_Ignorable_Code_Point 0 (ZWJ, variation selectors); East Asian
 *   Wide and Fullwidth 2 (every Emoji_Presentation emoji is W); else 1.
 * A variation selector 16 does not widen its base: glibc and xterm count
 * U+2764 U+FE0F as one cell (foot and kitty widen it only in grapheme mode,
 * ?2027).
 *
 * Layout: below U+40000, page c >> 8 is all width 1 (0), 2 (1) or 0 (2), or
 * 3 + a row of vt_width_bits with 2 bits a code point; above, only
 * U+E0000..E0FFF (tags, variation selectors supplement) is not 1. A lookup
 * is two loads, no search: it runs for every character outside ASCII. */
#ifndef VTWIDTH_H
#define VTWIDTH_H

%(page)s

%(bits)s

/* Display width: 0, 1 or 2 cells. */
static int vt_char_width(vt_u32 c)
{
    int p;
    if (c < 0x300)
        return 1;
    if (c >= 0x%(limit)XUL)
        return c >= 0xE0000UL && c <= 0xE0FFFUL ? 0 : 1;
    p = vt_width_page[c >> 8];
    if (p < 3)
        return p == 0 ? 1 : p == 1 ? 2 : 0;
    return (vt_width_bits[p - 3][(c & 0xFF) >> 2] >> ((c & 3) << 1)) & 3;
}

#endif
""" % {"v": VERSION, "page": page_tab, "bits": bits_tab, "limit": LIMIT}
    with open(os.path.join(ROOT, "engine", "vtwidth.h"), "w") as f:
        f.write(out)
    print("engine/vtwidth.h: Unicode %s, %d pages, %d mixed (%d bytes)"
          % (VERSION, len(index), len(pages), len(index) + 64 * len(pages)))


if __name__ == "__main__":
    main()
